[package]
name = "flash"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
iced = "0.13.1"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
